import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding FundingPro database...");

  // ── DONORS ──────────────────────────────────────────────────────────────────
  const donors = await Promise.all([
    prisma.donor.upsert({
      where: { id: "donor-undp" },
      update: {},
      create: {
        id: "donor-undp",
        name: "United Nations Development Programme",
        shortName: "UNDP",
        country: "International",
        website: "https://www.undp.org",
        description: "Программа развития ООН — ведущая международная организация в области устойчивого развития.",
        isActive: true,
      },
    }),
    prisma.donor.upsert({
      where: { id: "donor-eu" },
      update: {},
      create: {
        id: "donor-eu",
        name: "European Union",
        shortName: "EU",
        country: "European Union",
        website: "https://ec.europa.eu",
        description: "Европейский союз финансирует программы развития гражданского общества, экологии и образования.",
        isActive: true,
      },
    }),
    prisma.donor.upsert({
      where: { id: "donor-giz" },
      update: {},
      create: {
        id: "donor-giz",
        name: "Deutsche Gesellschaft für Internationale Zusammenarbeit",
        shortName: "GIZ",
        country: "Germany",
        website: "https://www.giz.de",
        description: "Германская организация по международному сотрудничеству — поддерживает устойчивое развитие.",
        isActive: true,
      },
    }),
    prisma.donor.upsert({
      where: { id: "donor-wb" },
      update: {},
      create: {
        id: "donor-wb",
        name: "World Bank",
        shortName: "World Bank",
        country: "International",
        website: "https://www.worldbank.org",
        description: "Всемирный банк предоставляет финансовую и техническую помощь развивающимся странам.",
        isActive: true,
      },
    }),
    prisma.donor.upsert({
      where: { id: "donor-swiss" },
      update: {},
      create: {
        id: "donor-swiss",
        name: "Swiss Embassy / SDC",
        shortName: "Swiss Embassy",
        country: "Switzerland",
        website: "https://www.eda.admin.ch",
        description: "Швейцарское агентство развития и сотрудничества поддерживает проекты в Центральной Азии.",
        isActive: true,
      },
    }),
  ]);
  console.log(`✅ ${donors.length} donors seeded`);

  // ── GRANTS ───────────────────────────────────────────────────────────────────
  const now = new Date();
  const grants = [
    {
      id: "grant-001",
      donorId: "donor-undp",
      title: "Поддержка гражданского общества Узбекистана",
      sector: ["Гражданское общество", "Демократия"],
      country: ["Uzbekistan"],
      amountMin: 10000,
      amountMax: 50000,
      currency: "USD",
      deadline: new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO"],
      description: "Грант для поддержки НКО в сфере развития гражданского общества, прозрачности и участия граждан.",
    },
    {
      id: "grant-002",
      donorId: "donor-undp",
      title: "Молодёжное предпринимательство и инновации",
      sector: ["Предпринимательство", "Молодёжь"],
      country: ["Uzbekistan", "Kazakhstan", "Kyrgyzstan"],
      amountMin: 5000,
      amountMax: 25000,
      currency: "USD",
      deadline: new Date(now.getTime() + 45 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "INDIVIDUAL"],
      description: "Финансирование молодёжных предпринимательских инициатив и стартапов в Центральной Азии.",
    },
    {
      id: "grant-003",
      donorId: "donor-eu",
      title: "EU4Business: Поддержка МСП Узбекистана",
      sector: ["Бизнес", "МСП"],
      country: ["Uzbekistan"],
      amountMin: 20000,
      amountMax: 100000,
      currency: "EUR",
      deadline: new Date(now.getTime() + 90 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["BUSINESS"],
      description: "Программа поддержки малого и среднего бизнеса через гранты, техническую помощь и обучение.",
    },
    {
      id: "grant-004",
      donorId: "donor-eu",
      title: "Зелёная экономика и климатические решения",
      sector: ["Экология", "Климат"],
      country: ["Uzbekistan", "Central Asia"],
      amountMin: 50000,
      amountMax: 300000,
      currency: "EUR",
      deadline: new Date(now.getTime() + 120 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "BUSINESS", "ACADEMIC"],
      description: "Поддержка проектов в сфере зелёной энергетики, устойчивого сельского хозяйства и климатической адаптации.",
    },
    {
      id: "grant-005",
      donorId: "donor-eu",
      title: "Образование и цифровые навыки",
      sector: ["Образование", "Цифровые технологии"],
      country: ["Uzbekistan"],
      amountMin: 15000,
      amountMax: 75000,
      currency: "EUR",
      deadline: new Date(now.getTime() + 75 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "ACADEMIC", "GOVERNMENT"],
      description: "Финансирование программ цифровой грамотности, профессионального обучения и инновационного образования.",
    },
    {
      id: "grant-006",
      donorId: "donor-giz",
      title: "Устойчивое управление водными ресурсами",
      sector: ["Вода", "Экология"],
      country: ["Uzbekistan", "Tajikistan"],
      amountMin: 30000,
      amountMax: 150000,
      currency: "EUR",
      deadline: new Date(now.getTime() + 100 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "GOVERNMENT", "ACADEMIC"],
      description: "Проекты по эффективному использованию водных ресурсов, ирригации и водоснабжению населения.",
    },
    {
      id: "grant-007",
      donorId: "donor-giz",
      title: "Развитие профессионального образования",
      sector: ["Образование", "Профессиональное обучение"],
      country: ["Uzbekistan"],
      amountMin: 25000,
      amountMax: 120000,
      currency: "EUR",
      deadline: new Date(now.getTime() + 85 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "ACADEMIC", "GOVERNMENT"],
      description: "Реформа системы профессионального образования и подготовки кадров для рынка труда.",
    },
    {
      id: "grant-008",
      donorId: "donor-giz",
      title: "Агробизнес и сельское развитие",
      sector: ["Сельское хозяйство", "Бизнес"],
      country: ["Uzbekistan"],
      amountMin: 20000,
      amountMax: 80000,
      currency: "EUR",
      deadline: new Date(now.getTime() + 55 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["BUSINESS", "NGO"],
      description: "Поддержка агропредприятий, фермерских кооперативов и инновационных агротехнологий.",
    },
    {
      id: "grant-009",
      donorId: "donor-wb",
      title: "Инфраструктура и городское развитие",
      sector: ["Инфраструктура", "Урбанизация"],
      country: ["Uzbekistan"],
      amountMin: 100000,
      amountMax: 500000,
      currency: "USD",
      deadline: new Date(now.getTime() + 150 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["GOVERNMENT", "NGO"],
      description: "Проекты городской инфраструктуры: транспорт, коммунальные услуги, общественные пространства.",
    },
    {
      id: "grant-010",
      donorId: "donor-wb",
      title: "Финансовая грамотность и доступ к услугам",
      sector: ["Финансы", "Образование"],
      country: ["Uzbekistan", "Central Asia"],
      amountMin: 10000,
      amountMax: 50000,
      currency: "USD",
      deadline: new Date(now.getTime() + 70 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "ACADEMIC"],
      description: "Программы повышения финансовой грамотности населения и расширения доступа к финансовым услугам.",
    },
    {
      id: "grant-011",
      donorId: "donor-swiss",
      title: "Гендерное равенство и расширение прав женщин",
      sector: ["Гендер", "Права человека"],
      country: ["Uzbekistan", "Tajikistan", "Kyrgyzstan"],
      amountMin: 15000,
      amountMax: 80000,
      currency: "CHF",
      deadline: new Date(now.getTime() + 95 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO"],
      description: "Поддержка организаций, работающих в сфере гендерного равенства, защиты прав женщин и экономической эмансипации.",
    },
    {
      id: "grant-012",
      donorId: "donor-swiss",
      title: "Здравоохранение и первичная медицинская помощь",
      sector: ["Здравоохранение"],
      country: ["Uzbekistan"],
      amountMin: 20000,
      amountMax: 100000,
      currency: "CHF",
      deadline: new Date(now.getTime() + 110 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "GOVERNMENT"],
      description: "Улучшение доступа к первичной медицинской помощи, особенно в отдалённых районах.",
    },
    {
      id: "grant-013",
      donorId: "donor-undp",
      title: "Цифровое государственное управление",
      sector: ["Цифровые технологии", "Государственное управление"],
      country: ["Uzbekistan"],
      amountMin: 30000,
      amountMax: 200000,
      currency: "USD",
      deadline: new Date(now.getTime() + 80 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["GOVERNMENT", "NGO"],
      description: "Цифровизация государственных услуг, электронное правительство, открытые данные.",
    },
    {
      id: "grant-014",
      donorId: "donor-eu",
      title: "Права человека и верховенство закона",
      sector: ["Права человека", "Правосудие"],
      country: ["Uzbekistan"],
      amountMin: 25000,
      amountMax: 120000,
      currency: "EUR",
      deadline: new Date(now.getTime() + 65 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO"],
      description: "Поддержка организаций по защите прав человека, юридической помощи и развитию гражданского права.",
    },
    {
      id: "grant-015",
      donorId: "donor-giz",
      title: "Туризм и культурное наследие",
      sector: ["Туризм", "Культура"],
      country: ["Uzbekistan"],
      amountMin: 10000,
      amountMax: 60000,
      currency: "EUR",
      deadline: new Date(now.getTime() + 40 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "BUSINESS", "GOVERNMENT"],
      description: "Развитие экотуризма, сохранение культурного наследия и поддержка туристической инфраструктуры.",
    },
    {
      id: "grant-016",
      donorId: "donor-wb",
      title: "Инклюзивное образование для детей с ОВЗ",
      sector: ["Образование", "Инклюзия"],
      country: ["Uzbekistan"],
      amountMin: 15000,
      amountMax: 70000,
      currency: "USD",
      deadline: new Date(now.getTime() + 130 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "ACADEMIC"],
      description: "Проекты по развитию инклюзивного образования и интеграции детей с ограниченными возможностями.",
    },
    {
      id: "grant-017",
      donorId: "donor-swiss",
      title: "Устойчивое сельское хозяйство и продовольственная безопасность",
      sector: ["Сельское хозяйство", "Продовольствие"],
      country: ["Uzbekistan", "Tajikistan"],
      amountMin: 25000,
      amountMax: 150000,
      currency: "CHF",
      deadline: new Date(now.getTime() + 105 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "BUSINESS", "GOVERNMENT"],
      description: "Органическое земледелие, улучшение продовольственной безопасности и агроэкология.",
    },
    {
      id: "grant-018",
      donorId: "donor-undp",
      title: "Климатическая адаптация и снижение рисков стихийных бедствий",
      sector: ["Климат", "Снижение рисков"],
      country: ["Uzbekistan", "Central Asia"],
      amountMin: 40000,
      amountMax: 200000,
      currency: "USD",
      deadline: new Date(now.getTime() + 140 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "GOVERNMENT", "ACADEMIC"],
      description: "Повышение устойчивости к климатическим изменениям и снижение уязвимости населения.",
    },
    {
      id: "grant-019",
      donorId: "donor-eu",
      title: "Инновации и технологическое предпринимательство",
      sector: ["Инновации", "Технологии"],
      country: ["Uzbekistan"],
      amountMin: 30000,
      amountMax: 150000,
      currency: "EUR",
      deadline: new Date(now.getTime() + 90 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["BUSINESS", "ACADEMIC"],
      description: "Поддержка технологических стартапов, R&D проектов и инновационных экосистем.",
    },
    {
      id: "grant-020",
      donorId: "donor-giz",
      title: "Возобновляемая энергетика для домохозяйств",
      sector: ["Энергетика", "Экология"],
      country: ["Uzbekistan"],
      amountMin: 20000,
      amountMax: 100000,
      currency: "EUR",
      deadline: new Date(now.getTime() + 75 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "BUSINESS"],
      description: "Солнечная энергия, малые ГЭС и другие ВИЭ-решения для домохозяйств и малого бизнеса.",
    },
    {
      id: "grant-021",
      donorId: "donor-swiss",
      title: "Права детей и защита уязвимых групп",
      sector: ["Права детей", "Социальная защита"],
      country: ["Uzbekistan"],
      amountMin: 10000,
      amountMax: 50000,
      currency: "CHF",
      deadline: new Date(now.getTime() + 55 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO"],
      description: "Защита прав детей, программы социальной поддержки уязвимых групп населения.",
    },
    {
      id: "grant-022",
      donorId: "donor-undp",
      title: "Развитие местного самоуправления",
      sector: ["Государственное управление", "Местное развитие"],
      country: ["Uzbekistan"],
      amountMin: 15000,
      amountMax: 80000,
      currency: "USD",
      deadline: new Date(now.getTime() + 85 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["GOVERNMENT", "NGO"],
      description: "Усиление потенциала местных органов власти и развитие территориального управления.",
    },
    {
      id: "grant-023",
      donorId: "donor-eu",
      title: "Медиа, свобода слова и журналистика",
      sector: ["Медиа", "Свобода слова"],
      country: ["Uzbekistan"],
      amountMin: 20000,
      amountMax: 100000,
      currency: "EUR",
      deadline: new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "INDIVIDUAL"],
      description: "Развитие независимых СМИ, цифровой журналистики и медиаграмотности.",
    },
    {
      id: "grant-024",
      donorId: "donor-wb",
      title: "Занятость молодёжи и профессиональные навыки",
      sector: ["Занятость", "Молодёжь"],
      country: ["Uzbekistan"],
      amountMin: 20000,
      amountMax: 100000,
      currency: "USD",
      deadline: new Date(now.getTime() + 95 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "BUSINESS", "ACADEMIC"],
      description: "Программы трудоустройства молодёжи, профессиональной ориентации и развития навыков.",
    },
    {
      id: "grant-025",
      donorId: "donor-giz",
      title: "Охрана биоразнообразия и экосистем",
      sector: ["Экология", "Биоразнообразие"],
      country: ["Uzbekistan", "Central Asia"],
      amountMin: 30000,
      amountMax: 180000,
      currency: "EUR",
      deadline: new Date(now.getTime() + 120 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "ACADEMIC", "GOVERNMENT"],
      description: "Сохранение биоразнообразия, особо охраняемые природные территории, экологические коридоры.",
    },
    {
      id: "grant-026",
      donorId: "donor-swiss",
      title: "Мир, диалог и предотвращение конфликтов",
      sector: ["Мир", "Диалог"],
      country: ["Uzbekistan", "Central Asia"],
      amountMin: 15000,
      amountMax: 70000,
      currency: "CHF",
      deadline: new Date(now.getTime() + 110 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO"],
      description: "Межнациональный диалог, миростроительство и снижение социальной напряжённости.",
    },
    {
      id: "grant-027",
      donorId: "donor-undp",
      title: "Цели устойчивого развития — ЦУР локализация",
      sector: ["Устойчивое развитие", "ЦУР"],
      country: ["Uzbekistan"],
      amountMin: 25000,
      amountMax: 150000,
      currency: "USD",
      deadline: new Date(now.getTime() + 130 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "GOVERNMENT", "ACADEMIC"],
      description: "Локализация и мониторинг Целей устойчивого развития на уровне регионов и местных сообществ.",
    },
    {
      id: "grant-028",
      donorId: "donor-eu",
      title: "Социальное предпринимательство",
      sector: ["Социальное предпринимательство"],
      country: ["Uzbekistan"],
      amountMin: 15000,
      amountMax: 60000,
      currency: "EUR",
      deadline: new Date(now.getTime() + 50 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO", "BUSINESS"],
      description: "Поддержка социальных предпринимателей и социально ориентированных бизнесов.",
    },
    {
      id: "grant-029",
      donorId: "donor-wb",
      title: "Цифровая трансформация здравоохранения",
      sector: ["Здравоохранение", "Цифровые технологии"],
      country: ["Uzbekistan"],
      amountMin: 50000,
      amountMax: 300000,
      currency: "USD",
      deadline: new Date(now.getTime() + 160 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["GOVERNMENT", "NGO", "BUSINESS"],
      description: "Цифровые решения для системы здравоохранения: телемедицина, медицинские данные, ИТ-инфраструктура.",
    },
    {
      id: "grant-030",
      donorId: "donor-giz",
      title: "Борьба с коррупцией и прозрачность",
      sector: ["Антикоррупция", "Прозрачность"],
      country: ["Uzbekistan"],
      amountMin: 10000,
      amountMax: 50000,
      currency: "EUR",
      deadline: new Date(now.getTime() + 70 * 24 * 60 * 60 * 1000),
      eligibleTypes: ["NGO"],
      description: "Антикоррупционные инициативы, прозрачность государственных закупок и общественный контроль.",
    },
  ];

  for (const g of grants) {
    await prisma.grant.upsert({
      where: { id: g.id },
      update: {},
      create: {
        id: g.id,
        title: g.title,
        donorId: g.donorId,
        description: g.description,
        sector: g.sector,
        country: g.country,
        amountMin: g.amountMin,
        amountMax: g.amountMax,
        currency: g.currency,
        deadline: g.deadline,
        eligibleTypes: g.eligibleTypes,
        isActive: true,
        isFeatured: ["grant-001", "grant-003", "grant-011", "grant-018"].includes(g.id),
        sourceUrl: `https://example.org/grants/${g.id}`,
      },
    });
  }
  console.log(`✅ ${grants.length} grants seeded`);

  // ── PLANS ────────────────────────────────────────────────────────────────────
  const plans = [
    {
      id: "plan-ngo-basic",
      name: "NGO Basic",
      nameRu: "НКО / Физлица Basic",
      targetType: "NGO" as const,
      priceUsd: 30,
      features: {
        grantAccess: true,
        eligibilityChecks: 5,
        proposalDrafts: 2,
        tracker: true,
        documents: false,
        consultation: false,
        aiRequests: 10,
      },
    },
    {
      id: "plan-ngo-pro",
      name: "NGO Pro",
      nameRu: "НКО / Физлица Pro",
      targetType: "NGO" as const,
      priceUsd: 50,
      features: {
        grantAccess: true,
        eligibilityChecks: -1,
        proposalDrafts: 10,
        tracker: true,
        documents: true,
        consultation: "1 час",
        aiRequests: 50,
      },
    },
    {
      id: "plan-consulting",
      name: "Consulting",
      nameRu: "Консалтинг",
      targetType: "INDIVIDUAL" as const,
      priceUsd: 100,
      features: {
        grantAccess: true,
        eligibilityChecks: -1,
        proposalDrafts: -1,
        tracker: true,
        documents: true,
        consultation: "3 часа",
        aiRequests: 100,
        prioritySupport: true,
      },
    },
    {
      id: "plan-business-starter",
      name: "Business Starter",
      nameRu: "Бизнес Starter",
      targetType: "BUSINESS" as const,
      priceUsd: 90,
      features: {
        grantAccess: true,
        eligibilityChecks: -1,
        proposalDrafts: 10,
        tracker: true,
        documents: true,
        consultation: "2 часа",
        aiRequests: 100,
        teamAccess: 3,
      },
    },
    {
      id: "plan-business-pro",
      name: "Business Pro",
      nameRu: "Бизнес Pro",
      targetType: "BUSINESS" as const,
      priceUsd: 200,
      features: {
        grantAccess: true,
        eligibilityChecks: -1,
        proposalDrafts: -1,
        tracker: true,
        documents: true,
        consultation: "5 часов",
        aiRequests: -1,
        teamAccess: 10,
        prioritySupport: true,
      },
    },
    {
      id: "plan-enterprise",
      name: "Enterprise",
      nameRu: "Enterprise",
      targetType: "ENTERPRISE" as const,
      priceUsd: 500,
      features: {
        grantAccess: true,
        eligibilityChecks: -1,
        proposalDrafts: -1,
        tracker: true,
        documents: true,
        consultation: "Неограниченно",
        aiRequests: -1,
        teamAccess: -1,
        prioritySupport: true,
        dedicatedManager: true,
      },
    },
  ];

  for (const p of plans) {
    await prisma.plan.upsert({
      where: { id: p.id },
      update: {},
      create: {
        id: p.id,
        name: p.name,
        nameRu: p.nameRu,
        targetType: p.targetType,
        priceUsd: p.priceUsd,
        billingPeriod: "monthly",
        features: p.features,
        isActive: true,
      },
    });
  }
  console.log(`✅ ${plans.length} plans seeded`);

  // ── SETTINGS ─────────────────────────────────────────────────────────────────
  const settings = [
    { key: "paymentIntegrationStatus", value: "pending", category: "payments" },
    { key: "paymentsEnabled", value: "false", category: "payments" },
    { key: "aiProviderStatus", value: "mock", category: "ai" },
    { key: "platformVersion", value: "1.0.0-beta", category: "general" },
    { key: "supportEmail", value: "info@fundingpro.uz", category: "general" },
    { key: "successFeeMin", value: "2", category: "pricing" },
    { key: "successFeeMax", value: "5", category: "pricing" },
  ];

  for (const s of settings) {
    await prisma.setting.upsert({
      where: { key: s.key },
      update: {},
      create: s,
    });
  }
  console.log(`✅ ${settings.length} settings seeded`);

  console.log("✅ Seeding complete!");
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
